In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [3]:
a=tf.Variable([3,4,5,6])

In [4]:
a.shape

TensorShape([4])

In [5]:
a.dtype

tf.int32

In [6]:
a.numpy()

array([3, 4, 5, 6])

In [7]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [8]:
a=tf.Variable(np.array([3,4,5,6]))

In [9]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([3, 4, 5, 6])>

In [11]:
t_f=tf.Variable([1.2,2,3,4,5])

In [12]:
t_f

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([1.2, 2. , 3. , 4. , 5. ], dtype=float32)>

In [14]:
t_s=tf.Variable(["a","b","c","d"])

In [15]:
t_s

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [16]:
t_b=tf.Variable([True,False])

In [17]:
t_b

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [19]:
t_cx=tf.Variable([3+4j])

In [20]:
t_cx

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

# Create tf from constant tensorflow variable

In [21]:
t_con=tf.constant([1,1,2,3,4])

In [22]:
t_con

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 2, 3, 4])>

In [23]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 1, 2, 3, 4])>

# create tf variable with different shahpe

In [25]:
t_2d=tf.Variable([[2,3],[3,4]])

In [26]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [3, 4]])>

In [27]:
t_2d=tf.Variable([[2,3],[4,5]],shape=(2,2),dtype="float32")

In [28]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [29]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([3, 4, 5, 6])>

In [31]:
tf.reshape(a, (2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

# get inded of highest value

In [34]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [35]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

In [36]:
tf.argmax(t_2d).numpy()

array([1, 1], dtype=int64)

# viewed/convert as tensor

In [37]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([3, 4, 5, 6])>

In [39]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6])>