In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.9.1'

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [4]:
a=tf.constant(10)

In [5]:
b=tf.constant(10.2)

In [6]:
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.2>

In [7]:
c=tf.constant("My name is Riad")

In [8]:
c

<tf.Tensor: shape=(), dtype=string, numpy=b'My name is Riad'>

In [9]:
d=tf.constant(True)

In [10]:
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [11]:
import numpy as np

In [12]:
e=tf.constant(np.array([3,4,5,6]))

In [13]:
e

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6])>

In [14]:
b=tf.constant([3,4,5,6])

In [15]:
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6])>

In [16]:
t_2d=tf.constant([[3,4],[5,6]])

In [17]:
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

In [18]:
t2=tf.constant([3,4,5,6],shape=(2,2),dtype="float64")

In [19]:
t2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3., 4.],
       [5., 6.]])>

In [20]:
t3=tf.constant([[[1,2],[2,3],[4,5]]],dtype="float64")

In [21]:
print(t3)

tf.Tensor(
[[[1. 2.]
  [2. 3.]
  [4. 5.]]], shape=(1, 3, 2), dtype=float64)


In [22]:
t3.numpy()

array([[[1., 2.],
        [2., 3.],
        [4., 5.]]])

In [23]:
t3.numpy()[0][2]

array([4., 5.])